/* * ======================================================================================
 * PROJECT: LODGING MANAGEMENT SYSTEM (LMS)
 * DATABASE: PostgreSQL
 * AUTHOR: trandnquang
 * VERSION: 1.1 (Refactored & Standardized)
 * * NOTES:
 * 1. Naming Convention: snake_case for all tables and columns.
 * 2. Audit Columns: All tables include created_at, updated_at, created_by, updated_by.
 * 3. Security: Passwords must be hashed (BCrypt) before insertion.
 * 4. Refactoring: 'Service' entity has been renamed to 'Utility' to avoid Spring keyword conflicts.
 * ======================================================================================
 */

-- [PART 1: CONFIGURATION & UTILITIES]

-- Enable UUID extension (recommended for scalable IDs in future)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to automatically update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- [PART 2: DDL - TABLES DEFINITION]

-- Drop tables in reverse dependency order to avoid foreign key constraints errors
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS invoice_detail CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS contract_utility CASCADE;
DROP TABLE IF EXISTS resident CASCADE;
DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS utility CASCADE;
DROP TABLE IF EXISTS tenant CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS property CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Table (Authentication & Authorization)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- BCrypt Hash
    full_name VARCHAR(100),
    avatar_url TEXT,

    -- [ENUM: UserStatus] - VALUES: ACTIVE, INACTIVE, BANNED
    status VARCHAR(20) DEFAULT 'ACTIVE',

    -- [ENUM: UserRole] - VALUES: ROLE_ADMIN, ROLE_MANAGER, ROLE_TENANT
    role VARCHAR(20) DEFAULT 'ROLE_MANAGER',

    -- Audit
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'SYSTEM',
    updated_by VARCHAR(50) DEFAULT 'SYSTEM'
);

-- 2. Property Table (Buildings / Apartment Complexes)
CREATE TABLE property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,

    -- Location (Using String for flexibility, validated by AddressService)
    address_line VARCHAR(255) NOT NULL,
    ward VARCHAR(100),
    district VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);
CREATE INDEX idx_property_location ON property(city, district);

-- 3. Room Table (Units within a Property)
CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,

    room_number VARCHAR(50) NOT NULL,
    floor_number INT DEFAULT 1,
    area NUMERIC(10, 2), -- Unit: Square meters (m2)

    -- Base price (Reference price, actual rent price is defined in Contract)
    base_price NUMERIC(15, 2) CHECK (base_price >= 0),

    capacity INT CHECK (capacity > 0),
    image_url TEXT,

    -- [ENUM: RoomStatus] - VALUES: AVAILABLE, OCCUPIED, MAINTENANCE, RESERVED
    status VARCHAR(50) DEFAULT 'AVAILABLE',

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_room_property FOREIGN KEY (property_id) REFERENCES property(id)
);

-- 4. Tenant Table (The main contract holder)
CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Personal Info
    identity_card_number VARCHAR(20) UNIQUE NOT NULL, -- ID Card / Passport / CCCD
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    email VARCHAR(100),
    birthday DATE,

    -- [ENUM: Gender] - VALUES: MALE, FEMALE, OTHER
    gender VARCHAR(10),

    -- Permanent Address (From ID Card)
    address_line VARCHAR(255),
    ward VARCHAR(100),
    district VARCHAR(100),
    city VARCHAR(100),

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

-- 5. Utility Table (Services like Electricity, Water, Internet)
-- Renamed from 'utility' to 'utility'
CREATE TABLE utility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,

    -- [ENUM: PricingType] - VALUES: FLAT (per unit), FIXED (monthly), TIERED (progressive)
    pricing_type VARCHAR(50) DEFAULT 'FLAT',

    unit VARCHAR(50), -- e.g., kWh, m3, person, room, month
    base_price NUMERIC(15, 2) DEFAULT 0,

    -- JSONB for Tiered Pricing Configuration
    -- Schema: [{"min": 0, "max": 50, "price": 1600}, {"min": 51, "max": 100, "price": 1700}]
    tier_config JSONB,

    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

-- 6. Contract Table (Lease Agreement)
CREATE TABLE contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,

    contract_code VARCHAR(50) UNIQUE, -- Auto-generated (e.g., HD-20250101-ABCD)

    -- Duration
    start_date DATE NOT NULL,
    end_date DATE, -- Can be NULL for indefinite contracts
    actual_end_date DATE, -- Used when contract is terminated early

    -- Financials (SNAPSHOT - Locked prices at signing)
    deposit_amount NUMERIC(15, 2) DEFAULT 0,
    rent_price NUMERIC(15, 2) NOT NULL, -- Agreed monthly rent
    payment_cycle INT DEFAULT 1, -- Billing cycle (1 month, 3 months...)

    -- [ENUM: ContractStatus] - VALUES: ACTIVE, EXPIRED, TERMINATED, PENDING
    status VARCHAR(50) DEFAULT 'ACTIVE',

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_contract_room FOREIGN KEY (room_id) REFERENCES room(id),
    CONSTRAINT fk_contract_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

-- 7. Contract Utility (Utilities assigned to a specific contract)
-- Renamed from 'contract_service'
CREATE TABLE contract_utility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    utility_id BIGINT NOT NULL,

    amount INT DEFAULT 1, -- Quantity (e.g., number of people or vehicles)

    -- [SNAPSHOT] Initial index recording for meter-based utilities
    start_index NUMERIC(10, 2) DEFAULT 0,

    -- Audit
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_cu_contract FOREIGN KEY (contract_id) REFERENCES contract(id),
    CONSTRAINT fk_cu_utility FOREIGN KEY (utility_id) REFERENCES utility(id)
);

-- 8. Resident Table (Actual occupants, might differ from Tenant)
CREATE TABLE resident (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,

    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15),
    identity_card_number VARCHAR(20),

    is_contract_holder BOOLEAN DEFAULT FALSE,

    move_in_date DATE DEFAULT CURRENT_DATE,
    move_out_date DATE,

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_resident_contract FOREIGN KEY (contract_id) REFERENCES contract(id)
);

-- 9. Invoice Table (Monthly Bills)
CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,

    invoice_code VARCHAR(50) UNIQUE, -- Format: INV-YYYYMM-XXXX
    month INT NOT NULL,
    year INT NOT NULL,

    issue_date DATE DEFAULT CURRENT_DATE,
    due_date DATE,

    -- Amounts
    total_amount NUMERIC(15, 2) DEFAULT 0,
    paid_amount NUMERIC(15, 2) DEFAULT 0,
    -- Generated Column: Auto-calculate remaining amount
    remaining_amount NUMERIC(15, 2) GENERATED ALWAYS AS (total_amount - paid_amount) STORED,

    -- [ENUM: InvoiceStatus] - VALUES: DRAFT, SENT, PARTIAL, PAID, OVERDUE, CANCELLED
    status VARCHAR(50) DEFAULT 'DRAFT',

    -- Audit
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_invoice_contract FOREIGN KEY (contract_id) REFERENCES contract(id)
);

-- 10. Invoice Detail (Line items for each utility/rent in an invoice)
CREATE TABLE invoice_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    utility_id BIGINT, -- Nullable (e.g., for Rent or Custom Fees)

    utility_name VARCHAR(255), -- Snapshot of the utility name

    -- Meter readings
    old_index NUMERIC(10, 2) DEFAULT 0,
    new_index NUMERIC(10, 2) DEFAULT 0,
    -- Generated Column: usage = new - old
    usage_amount NUMERIC(10, 2) GENERATED ALWAYS AS (new_index - old_index) STORED,

    -- [SNAPSHOT] Price applied for this specific month
    applied_price NUMERIC(15, 2),

    total_price NUMERIC(15, 2), -- Calculation: usage * applied_price OR fixed amount

    description TEXT,

    -- Audit
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_detail_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

-- 11. Payment Table (Payment Transaction History)
CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,

    amount NUMERIC(15, 2) CHECK (amount > 0),

    -- [ENUM: PaymentMethod] - VALUES: CASH, BANK_TRANSFER, QR_CODE
    payment_method VARCHAR(50),

    transaction_code VARCHAR(100), -- Reference code from bank
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    note TEXT,

    -- Audit
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),

    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

-- [PART 3: TRIGGERS FOR AUTO-UPDATING TIMESTAMP]
CREATE TRIGGER update_users_modtime BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_property_modtime BEFORE UPDATE ON property FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_room_modtime BEFORE UPDATE ON room FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_tenant_modtime BEFORE UPDATE ON tenant FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_utility_modtime BEFORE UPDATE ON utility FOR EACH ROW EXECUTE PROCEDURE update_timestamp(); -- Corrected table name
CREATE TRIGGER update_contract_modtime BEFORE UPDATE ON contract FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_resident_modtime BEFORE UPDATE ON resident FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_invoice_modtime BEFORE UPDATE ON invoice FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- [PART 4: SEED DATA (English)]

-- 1. Admin User
-- Password: 'password123' (BCrypt hashed)
INSERT INTO users (username, email, password_hash, full_name, role)
VALUES ('admin', 'admin@lms.com', '$2a$12$8W.Y/a.2L.1.3/2.3.4.5.6.7.8.9.0.1.2.3.4.5.6.7.8.9.0', 'System Admin', 'ROLE_ADMIN');

-- 2. Property
INSERT INTO property (name, address_line, district, city, created_by)
VALUES ('Sunrise Apartments', '100 Nguyen Hue Street', 'Vinh Ninh', 'Hue', 'admin');

-- 3. Room
INSERT INTO room (property_id, room_number, area, base_price, capacity, created_by)
VALUES
(1, '101', 25.5, 2500000, 2, 'admin'),
(1, '102', 30.0, 3000000, 3, 'admin');

-- 4. Utility (Formerly Service)
INSERT INTO utility (name, pricing_type, unit, base_price, tier_config, created_by) VALUES
('Residential Electricity', 'TIERED', 'kWh', 0, '[{"min":0, "max":50, "price":1678}, {"min":51, "max":100, "price":1734}]', 'admin'),
('Water', 'FLAT', 'm3', 10000, NULL, 'admin'),
('Internet', 'FIXED', 'Month', 150000, NULL, 'admin');

-- 5. Tenant
INSERT INTO tenant (identity_card_number, full_name, phone_number, gender, created_by)
VALUES ('046099123456', 'John Doe', '0905111222', 'MALE', 'admin');

-- 6. Contract
-- Assumes Room ID 1 and Tenant ID 1 exist from above inserts
INSERT INTO contract (room_id, tenant_id, contract_code, start_date, rent_price, deposit_amount, created_by)
VALUES (1, 1, 'CT-2025-001', '2025-01-01', 2500000, 2500000, 'admin');