/* * LMS Database Setup Script
 * Updated: Address Atomicity & Room Detail Enhancement
 * Standard: Global Basic (English, Snake_case, Singular)
 */

-- [PART 1: DDL - Data Definition Language]

-- Clean up existing tables (Order matters due to FK constraints)
DROP TABLE IF EXISTS invoice_item CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS service_subscription CASCADE;
DROP TABLE IF EXISTS service CASCADE;
DROP TABLE IF EXISTS resident CASCADE;
DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS tenant CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS property CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;

-- 0. User Account Table (For authentication)
CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL, 
    full_name VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1. Property Table
-- Updated: Split address into administrative units
CREATE TABLE property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address_line VARCHAR(255) NOT NULL, -- Street name, house number
    ward VARCHAR(100),
    district VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,         -- Province/City
    description TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_property_location ON property(city, district);

-- 2. Room Table
-- Updated: Added floor_number and area (sqm)
CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    room_number VARCHAR(50) NOT NULL,
    floor_number INT,                   -- 0 for Ground, 1 for 1st floor...
    area NUMERIC(10, 2),                -- Area in square meters (m2)
    price NUMERIC(15, 2) CHECK (price >= 0),
    capacity INT CHECK (capacity > 0),
    image_url TEXT,
    status VARCHAR(50) DEFAULT 'AVAILABLE', 
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_room_property FOREIGN KEY (property_id) REFERENCES property(id)
);
CREATE INDEX idx_room_property ON room(property_id);

-- 3. Tenant Table
-- Updated: Split address similar to Property
CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_number VARCHAR(20) UNIQUE NOT NULL, -- CCCD/Passport
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15),
    email VARCHAR(100),
    address_line VARCHAR(255),
    ward VARCHAR(100),
    district VARCHAR(100),
    city VARCHAR(100),
    gender VARCHAR(10),
    date_of_birth DATE,
    is_deleted BOOLEAN DEFAULT FALSE
);
CREATE INDEX idx_tenant_identity ON tenant(identity_number);

-- 4. Contract Table
CREATE TABLE contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL, 
    start_date DATE NOT NULL,
    end_date DATE,
    deposit NUMERIC(15, 2) DEFAULT 0,
    occupant_count INT DEFAULT 1,
    rent_price NUMERIC(15, 2) NOT NULL,
    contract_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(50) DEFAULT 'ACTIVE', -- ACTIVE, EXPIRED, TERMINATED
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_contract_room FOREIGN KEY (room_id) REFERENCES room(id),
    CONSTRAINT fk_contract_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

-- 5. Resident Table (People living in the room, can include the tenant)
CREATE TABLE resident (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    role VARCHAR(50) DEFAULT 'MEMBER', -- 'LEADER' or 'MEMBER'
    move_in_date DATE DEFAULT CURRENT_DATE,
    move_out_date DATE,
    CONSTRAINT fk_resident_contract FOREIGN KEY (contract_id) REFERENCES contract(id),
    CONSTRAINT fk_resident_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

-- 6. Service Table
CREATE TABLE service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(15, 2) NOT NULL CHECK (price >= 0),
    unit VARCHAR(50), 
    is_deleted BOOLEAN DEFAULT FALSE
);

-- 7. Service Subscription (Connecting Contract & Service)
CREATE TABLE service_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    quantity INT DEFAULT 1,
    fixed_price NUMERIC(15, 2), -- Optional: if price differs from base service price
    start_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    CONSTRAINT fk_sub_contract FOREIGN KEY (contract_id) REFERENCES contract(id),
    CONSTRAINT fk_sub_service FOREIGN KEY (service_id) REFERENCES service(id)
);

-- 8. Invoice Table
CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    issue_date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    total_amount NUMERIC(15, 2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'UNPAID', -- UNPAID, PARTIAL, PAID, OVERDUE
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_invoice_contract FOREIGN KEY (contract_id) REFERENCES contract(id)
);

-- 9. Payment Table
CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    payment_date DATE DEFAULT CURRENT_DATE,
    amount NUMERIC(15, 2) CHECK (amount > 0),
    method VARCHAR(100), -- 'CASH', 'BANK_TRANSFER', 'QR'
    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

-- 10. Invoice Detail Items
CREATE TABLE invoice_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    old_value INT DEFAULT 0, -- For meter readings (electricity/water)
    new_value INT DEFAULT 0,
    unit_price NUMERIC(15, 2),
    sub_total NUMERIC(15, 2),
    note TEXT,
    CONSTRAINT fk_item_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    CONSTRAINT fk_item_service FOREIGN KEY (service_id) REFERENCES service(id)
);

-- [PART 2: DML - Seed Data]

-- Seed Property (Updated address structure)
INSERT INTO property (name, address_line, ward, district, city) 
VALUES ('LMS Demo Apartment', '123 Hue Street', 'Phu Hoi Ward', 'Hue City', 'Thua Thien Hue');

-- Seed Room (Updated floor and area)
INSERT INTO room (property_id, room_number, floor_number, area, price, capacity, status) 
VALUES 
(1, 'A.101', 1, 30.5, 3500000, 3, 'OCCUPIED'),
(1, 'A.201', 2, 35.0, 4000000, 4, 'AVAILABLE');

-- Seed Tenant (Updated address structure)
INSERT INTO tenant (identity_number, full_name, phone_number, email, address_line, ward, district, city, gender) 
VALUES ('046099000001', 'Nguyen Van A', '0905123456', 'vana@email.com', '456 Le Loi', 'Vinh Ninh', 'Hue City', 'Thua Thien Hue', 'MALE');

-- Seed Service
INSERT INTO service (name, price, unit) 
VALUES ('Electricity', 3500, 'kWh'), ('Water', 10000, 'm3'), ('Internet', 100000, 'Month');

-- Seed Contract
INSERT INTO contract (room_id, tenant_id, start_date, rent_price, deposit) 
VALUES (1, 1, '2025-01-01', 3500000, 3500000);