/* * LMS Database Setup Script
 * Database: PostgreSQL
 * Author: LMS Assistant (BrSE Mentor)
 * Description: Creates tables, constraints, indexes, and seed demo data.
 */

-- [Phần 1: DDL - Data Definition Language]
-- Xóa bảng cũ nếu tồn tại để tránh lỗi khi chạy lại (Clean slate)
DROP TABLE IF EXISTS chi_tiet_hoa_don CASCADE;
DROP TABLE IF EXISTS phieu_thu CASCADE;
DROP TABLE IF EXISTS hoa_don CASCADE;
DROP TABLE IF EXISTS dich_vu_dang_ky CASCADE;
DROP TABLE IF EXISTS dich_vu CASCADE;
DROP TABLE IF EXISTS cu_dan CASCADE;
DROP TABLE IF EXISTS hop_dong CASCADE;
DROP TABLE IF EXISTS nguoi_thue CASCADE;
DROP TABLE IF EXISTS phong_tro CASCADE;
DROP TABLE IF EXISTS nha_tro CASCADE;

-- 1. Bang nha_tro (Master Data)
CREATE TABLE nha_tro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_nha VARCHAR(255) NOT NULL,
    dia_chi TEXT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE
);
-- Index tìm kiếm theo tên nhà
CREATE INDEX idx_nhatro_ten ON nha_tro(ten_nha);

-- 2. Bang phong_tro
CREATE TABLE phong_tro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nha_tro BIGINT NOT NULL,
    ten_phong VARCHAR(50) NOT NULL,
    gia_thue_phong NUMERIC(15, 2) CHECK (gia_thue_phong >= 0),
    so_nguoi_toi_da INT CHECK (so_nguoi_toi_da > 0),
    tinh_trang_phong VARCHAR(50) DEFAULT 'Con trong', -- Enum: 'Da cho thue', 'Con trong'
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_phongtro_nhatro FOREIGN KEY (id_nha_tro) REFERENCES nha_tro(id)
);
CREATE INDEX idx_phongtro_nhatro ON phong_tro(id_nha_tro);

-- 3. Bang nguoi_thue
CREATE TABLE nguoi_thue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cccd VARCHAR(20) UNIQUE NOT NULL, -- CCCD phải là duy nhất
    ho_ten VARCHAR(255) NOT NULL,
    so_dien_thoai VARCHAR(15),
    email VARCHAR(100),
    dia_chi TEXT,
    gioi_tinh VARCHAR(10),
    ngay_sinh DATE,
    is_deleted BOOLEAN DEFAULT FALSE
);
CREATE INDEX idx_nguoithue_cccd ON nguoi_thue(cccd);
CREATE INDEX idx_nguoithue_sdt ON nguoi_thue(so_dien_thoai);

-- 4. Bang hop_dong
CREATE TABLE hop_dong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_phong_tro BIGINT NOT NULL,
    id_nguoi_thue BIGINT NOT NULL, -- Người đại diện ký hợp đồng
    ngay_bat_dau DATE NOT NULL,
    ngay_ket_thuc DATE,
    tien_coc NUMERIC(15, 2) DEFAULT 0,
    so_nguoi INT DEFAULT 1,
    gia_thue_chot NUMERIC(15, 2) NOT NULL, -- Giá tại thời điểm ký
    ngay_lap_hop_dong DATE DEFAULT CURRENT_DATE,
    trang_thai_hop_dong VARCHAR(50) DEFAULT 'Con hieu luc', -- Enum: 'Con hieu luc', 'Sap het han', 'Da het han'
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_hopdong_phongtro FOREIGN KEY (id_phong_tro) REFERENCES phong_tro(id),
    CONSTRAINT fk_hopdong_nguoithue FOREIGN KEY (id_nguoi_thue) REFERENCES nguoi_thue(id)
);
CREATE INDEX idx_hopdong_phong ON hop_dong(id_phong_tro);

-- 5. Bang cu_dan (Mapping table: Ai đang ở phòng nào)
CREATE TABLE cu_dan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hop_dong BIGINT NOT NULL,
    id_nguoi_thue BIGINT NOT NULL,
    vai_tro VARCHAR(50) DEFAULT 'Thanh vien', -- 'Nguoi dai dien', 'Thanh vien'
    ngay_vao DATE DEFAULT CURRENT_DATE,
    ngay_roi_di DATE,
    CONSTRAINT fk_cudan_hopdong FOREIGN KEY (id_hop_dong) REFERENCES hop_dong(id),
    CONSTRAINT fk_cudan_nguoithue FOREIGN KEY (id_nguoi_thue) REFERENCES nguoi_thue(id)
);

-- 6. Bang dich_vu (Master Data)
CREATE TABLE dich_vu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dich_vu VARCHAR(255) NOT NULL,
    don_gia NUMERIC(15, 2) NOT NULL CHECK (don_gia >= 0),
    don_vi_tinh VARCHAR(50), -- 'kWh', 'm3', 'Nguoi', 'Phong'
    is_deleted BOOLEAN DEFAULT FALSE
);

-- 7. Bang dich_vu_dang_ky (Dịch vụ gắn với Hợp đồng cụ thể)
CREATE TABLE dich_vu_dang_ky (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hop_dong BIGINT NOT NULL,
    id_dich_vu BIGINT NOT NULL,
    so_luong INT DEFAULT 1, -- Với điện nước thường là 1 (đồng hồ), với rác có thể là số người
    don_gia_chot NUMERIC(15, 2), -- Giá chốt tại thời điểm đăng ký
    ngay_dang_ky DATE DEFAULT CURRENT_DATE,
    ngay_ket_thuc DATE,
    trang_thai VARCHAR(50) DEFAULT 'Dang su dung',
    CONSTRAINT fk_dvdk_hopdong FOREIGN KEY (id_hop_dong) REFERENCES hop_dong(id),
    CONSTRAINT fk_dvdk_dichvu FOREIGN KEY (id_dich_vu) REFERENCES dich_vu(id)
);

-- 8. Bang hoa_don
CREATE TABLE hoa_don (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hop_dong BIGINT NOT NULL,
    ngay_lap_don DATE DEFAULT CURRENT_DATE,
    tong_tien NUMERIC(15, 2) DEFAULT 0,
    ngay_thanh_toan DATE,
    tinh_trang_hoa_don VARCHAR(50) DEFAULT 'Chua thanh toan',
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_hoadon_hopdong FOREIGN KEY (id_hop_dong) REFERENCES hop_dong(id)
);

-- 9. Bang phieu_thu
CREATE TABLE phieu_thu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hoa_don BIGINT NOT NULL,
    ngay_thu DATE DEFAULT CURRENT_DATE,
    so_tien_thu NUMERIC(15, 2) CHECK (so_tien_thu > 0),
    hinh_thuc VARCHAR(100), -- 'Tien mat', 'Chuyen khoan'
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_phieuthu_hoadon FOREIGN KEY (id_hoa_don) REFERENCES hoa_don(id)
);

-- 10. Bang chi_tiet_hoa_don
CREATE TABLE chi_tiet_hoa_don (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hoa_don BIGINT NOT NULL,
    id_dich_vu BIGINT NOT NULL,
    ghi_chu TEXT,
    chi_so_cu INT DEFAULT 0,
    chi_so_moi INT DEFAULT 0,
    don_gia_luu_tru NUMERIC(15, 2), -- Lưu lại giá lúc tính tiền
    thanh_tien NUMERIC(15, 2),
    CONSTRAINT fk_cthd_hoadon FOREIGN KEY (id_hoa_don) REFERENCES hoa_don(id),
    CONSTRAINT fk_cthd_dichvu FOREIGN KEY (id_dich_vu) REFERENCES dich_vu(id)
);

-- [Phần 2: DML - Data Manipulation Language - Seed Data]
-- Chèn dữ liệu mẫu theo kịch bản: 
-- 1 Nhà trọ, 1 Phòng A.101, 2 Cư dân (A & B), 2 Dịch vụ (Điện, Nước)

-- 1. Insert Nhà trọ
INSERT INTO nha_tro (ten_nha, dia_chi) 
VALUES ('Nhà trọ Demo', '123 Đường Huế, TP Huế');

-- 2. Insert Phòng trọ (Liên kết với Nhà trọ ID = 1)
INSERT INTO phong_tro (id_nha_tro, ten_phong, gia_thue_phong, so_nguoi_toi_da, tinh_trang_phong) 
VALUES (1, 'A.101', 3500000, 3, 'Da cho thue');

-- 3. Insert Người thuê (Cư dân)
-- Người 1: Nguyễn Văn A (Đại diện)
INSERT INTO nguoi_thue (cccd, ho_ten, so_dien_thoai, email, gioi_tinh) 
VALUES ('046099000001', 'Nguyễn Văn A', '0905123456', 'nguyenvana@email.com', 'Nam');

-- Người 2: Trương Thị B (Ở cùng)
INSERT INTO nguoi_thue (cccd, ho_ten, so_dien_thoai, email, gioi_tinh) 
VALUES ('046099000002', 'Trương Thị B', '0905987654', 'truongthib@email.com', 'Nu');

-- 4. Insert Dịch vụ Master
INSERT INTO dich_vu (ten_dich_vu, don_gia, don_vi_tinh) VALUES 
('Tiền điện', 3500, 'kWh'),
('Tiền nước', 10000, 'm3');

-- 5. Insert Hợp đồng (Phòng 1 thuê bởi Người 1)
INSERT INTO hop_dong (id_phong_tro, id_nguoi_thue, ngay_bat_dau, ngay_ket_thuc, tien_coc, so_nguoi, gia_thue_chot, trang_thai_hop_dong)
VALUES (1, 1, '2025-01-01', '2026-01-01', 3500000, 2, 3500000, 'Con hieu luc');

-- 6. Insert Cư dân (Chi tiết ai đang ở trong Hợp đồng 1)
-- Insert ông A (Đại diện)
INSERT INTO cu_dan (id_hop_dong, id_nguoi_thue, vai_tro, ngay_vao)
VALUES (1, 1, 'Nguoi dai dien', '2025-01-01');

-- Insert bà B (Thành viên)
INSERT INTO cu_dan (id_hop_dong, id_nguoi_thue, vai_tro, ngay_vao)
VALUES (1, 2, 'Thanh vien', '2025-01-01');

-- 7. Insert Dịch vụ đăng ký (Gắn Điện & Nước vào Hợp đồng này)
-- Đăng ký điện
INSERT INTO dich_vu_dang_ky (id_hop_dong, id_dich_vu, don_gia_chot, ngay_dang_ky)
VALUES (1, 1, 3500, '2025-01-01');

-- Đăng ký nước
INSERT INTO dich_vu_dang_ky (id_hop_dong, id_dich_vu, don_gia_chot, ngay_dang_ky)
VALUES (1, 2, 10000, '2025-01-01');

-- (Chưa insert Hóa đơn và Phiếu thu theo yêu cầu)